# Identificación del proyecto
sonar.projectKey=mi-proyecto
sonar.projectName=Mi Proyecto Java

# Código fuente y tests
sonar.sources=src/main/java
sonar.tests=src/test/java

# Clases compiladas (para mapear cobertura)
sonar.java.binaries=target/classes

# Importar reporte JaCoCo en formato XML
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# (Opcional) Excluir archivos o paquetes
sonar.coverage.exclusions=**/dto/**,**/config/**

sonar.coverage.minimum=80
